### ISSUE TITLE
Migrate to NextJS

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#1]
When developing and managing openrevolution.net (which is now likely as things develop) I want to use a simple, flexible framework and supports tailwind so that I can make it look nice and rapidly add new features (see more in Why item below)

## Tasks

Prep

* [x] Why make this change? **Want to design more nicely and do in tailwind and not sure how to do in hugo. Not comfortable with Hugo in general which keeps changing. Know NextJS well. We want to make a richer site that incorporates imed, etc ...**
* [x] Decide whether to start anew or evolve hugo repo **Let's evolve for now. Can always reboot from clean once done**
* [x] Evaluate how many pages are invovled and any gotchas **See analysis and plan below**
* [x] Plan of migration

Implement

* [x] Stub site
* [x] Implement basic theme using front page as demo
* [x] Implement content pages
  * [x] review current pages and check markdown
  * [x] copy into content directory
  * [x] migrate static stuff
* [x] nav links
* [x] Implement google analytics (todo: check if i still use universal with my nextjs setup ...)

Content

- [x] _index.md ❌
- [x] contact.md 👍 
- [x] events.md 👍 
- [x] faq **~~Needs work as was split into parts~~ Consolidated into one file**
  - [x] remuneration-rights 👍 
- [x] kronos-effect.md **Add title and tweak text**
- [ ] make-it-happen.md **Degrades ok without its nice CSS but will need more work. TODO**
- [x] news **~~Needs specific work~~ DONE**
- [x] newsletter.md **Removed style attribute**
- [x] pay-what-feels-right - migrated from hugo layout
- [x] press.md **Fix toc and style**
- [x] preview.md **Fix ToC**
- [x] remuneration-rights.md 👍

## Analysis

`content/` contains

```
_index.md
contact.md
events.md
faq
kronos-effect.md
make-it-happen.md
news
newsletter.md
pay-what-feels-right
press.md
preview.md
remuneration-rights.md
```
