### ISSUE TITLE
v1.1 of NextJS (use Flowershow)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#12]
Migrate Open revolution/Diginomics to Flowershow

## Acceptance

- [x] Site is still functional and looks acceptable

## Tasks

- [x] Migrate to flowershow
- [x] blogs working **all blogposts except matrix-new-vector-real-time-chat-open-decentralized which is throwing a hydration error**
- [x] pages working
  - [x] kronos-effect has hydration error
  - [x] press has hydration error
  - [x] remuneration-rights has hydration error
  - [x] index page has reference error
- [x] fix life itself logo display

**Comment by PhilippeduPreez** [comment]
@rufuspollock It seems that when using `$` signs or `~`, svgs are created inside a mjx-container for the dollar amount, which causes the hydration errors atm. Putting them inside ` ` removes the error, but is probably not the best long term solution
