### ISSUE TITLE
Merge IMED project (imedproject.org) into the Open Revolution

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#2]
IMED (http://imedproject.org) is Open Revolution model for medicines so makes sense to integrate this content and project into the main open revolution site under the healthcare/medicines section.

## Acceptance

* [ ] All imedproject.org content is migrated to an appropriate location
* [ ] imedproject.org redirects appropriately (preserve as many urls as possible)
* [ ] Clear credit in appropriate section of site to original funders

## Tasks

- [ ] Plan migration
- [ ] Migrate content
- [ ] Retheme if appropriate
- [ ] Implement redirect
