### ISSUE TITLE
Library (e.g. in Zotero)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#23]
We want a library / reference manager for diginomics and use this as the primary storage for reference material.

## Acceptance

- [x] We have an online shared reference library **✅2023-01-10 https://www.zotero.org/groups/1488082/diginomics/library**
- [x] We have a page on the site e.g. `/notes/library/` referencing this and our process (can take inspiration from https://web3.lifeitself.org/library) **✅2023-01-19 see https://diginomics.io/library**

Bonus

- [ ] We have a process for using this library in our work (and documented in e.g. the library page) - cf https://github.com/flowershow/flowershow/issues/340

## Tasks

Setup

- [x] Choose reference manager **✅2023-01-10 use zotero as good, open source and we are already using**
- [x] Create a zotero library **✅2023-01-10 Already have a zotero library called open-world with subcollections and we can rename to diginomics**
- [x] Rename to diginomics
- [x] Share with @theo-cox **✅2023-01-10**

Site page

- [x] Page on site **✅2023-01-19 see https://diginomics.io/library**

**Comment by rufuspollock** [comment]
@theo-cox have you joined this library now?

**Comment by rufuspollock** [comment]
FIXED. Library set up and page up at https://diginomics.io/library
