### ISSUE TITLE
[inbox] Site Improvements (re Open Revolution)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#25]
## Tasks

* [ ] aspect ratio for youtube videos as per https://www.themes.dev/blog/easily-embed-responsive-youtube-video-with-tailwind-css/
* [ ] footer
  * [ ] social media links
* [ ] hero
  * [ ] As covered by ...
  * [ ] social media links

Bonus

* [ ] favicon (can be based on github icon)

WONTFIX

* [ ] (?) sticky navbar

Future

* [ ] buy page with various options
