### ISSUE TITLE
Post announcing the diginomics project

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#29]
Short post introducing the mechanism design-baking analogy.

## Acceptance

- [x] Post drafted
- [ ] Post published on diginomics
## Tasks

- [x] Create a draft **https://docs.google.com/document/d/1OY3V4jgKH66LM-0fwqCtAFF-bj5TjR5TJq1idxA6nyQ/edit**
- [x] Publish **https://github.com/life-itself/diginomics/blob/main/content/notes/mechanisms-bread.md**

**Comment by theo-cox** [comment]
@rufuspollock I've linked the draft, with two points at which we could end it based on what we think the attention span of our audience is. Request you skim and help me choose the cutoff point, and I can make final edits tomorrow ready to ship e.g. Monday

**Comment by rufuspollock** [comment]
@theo-cox i suggest you run with this - i'm sure it is good 😄

**Comment by rufuspollock** [comment]
@theo-cox also to check is the post announcing diginomics or the post announcing the taxonomy part - i thought it was the latter which is either a separate issue or part of #22 

BTW a post announcing the overall diginomics effort is also worth doing though less a priority.

**Comment by theo-cox** [comment]
FIXED. This is now published; site is building at time of wrting.
