### ISSUE TITLE
Landing page for diginomics site v0.1

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#35]
Landing page for new diginomics site

**UPDATE:  2023-05-03we did a basic version of this ... and now superseded by #84**

## Acceptance

- [x] New landing page for diginomics site
- [x] Hero section with call to action

## Tasks

- [x] Create v0.1
- [ ] Post about it! 📣 **Brainstorm trailer posts in https://github.com/life-itself/diginomics/issues/36**
- [ ] Create v0.2
- [ ] Post about it! 📣

### V0.1

Mockup

- [x] Wireframe ✅2023-01-31 https://app.excalidraw.com/l/9u8crB2ZmUo/AS49XMqTYbf
- [x] Content **✅2023-02-01 see https://app.excalidraw.com/s/9u8crB2ZmUo/AS49XMqTYbf which has key items there**
	- [x] Subject (which gives tagline and short blurb)
	- [x] Image **UPDATED 3 Feb - see below**
	  - [x] Update to new image 
	- [x] Call to action **🚧2023-02-04 have form but info does not go anywhere** **✅2023-02-13 have it working with basin**
	  - [x] select form service (either sendinblue or usebasin) **✅2023-02-13 used basin for now. tried setting up sendinblue and looked promising e.g. can get actual html. however need to restyle etc. could probably get this working but would take longer**
- [x] Mockup e.g. colors etc

Implement

- [x] create initially at e.g. /home-new/ and submit PR for review
- [x] Move to front page
  - [x] Move current front page to /open-revolution/
    - [x] Update navbar
    - [ ] ?? update redirects for openrevolution.net to go to diginomics.io/open-revolution/ 

### v0.2

add more content e.g. Recipe guide for aspiring database / data ecosystem builders: step by step guide to building your incentives etc.

- [ ] 1st twitter essay (which gives some content) - see next item **Draft now on excalidraw https://app.excalidraw.com/l/9u8crB2ZmUo/AS49XMqTYbf**
- [ ] Tidy
- [ ] Do link-out pages 
     - [ ]  Agree on which pages to do
     - [ ] Draft pages **First one on why data is different draft here: https://docs.google.com/document/d/17Kvy1BGFx33aKIi30Vt1PsSnYAOJplZrxAoWVjlZEOE/edit**
- [ ] Call to action (if any)
- [ ] Implement onto site (ourselves)

### Images for front page

![undraw_teaching_re_g7e3](https://user-images.githubusercontent.com/72795023/216580091-2b33a410-7d53-4e4b-b697-a93eadcd7856.svg)

**Comment by theo-cox** [comment]
Step by step guide now in excalidraw: [app.excalidraw.com/l/9u8crB2ZmUo/AS49XMqTYbf](https://app.excalidraw.com/l/9u8crB2ZmUo/AS49XMqTYbf)

Draft of first linked out page for why data is different also donehttps://docs.google.com/document/d/17Kvy1BGFx33aKIi30Vt1PsSnYAOJplZrxAoWVjlZEOE/edit

**Comment by theo-cox** [comment]
@rufuspollock updated image now in issue

**Comment by rufuspollock** [comment]
First effort Feb 2023

![image](https://user-images.githubusercontent.com/180658/235933417-feaf67f1-461d-44b5-ae92-f5af029cc264.png)

**Comment by rufuspollock** [comment]
FIXED. Have a basic new home page.

![image](https://user-images.githubusercontent.com/180658/235954760-a31043f0-cab7-4239-97d5-e7098663c2d2.png)
