### ISSUE TITLE
Content to reuse from Web3

### ISSUE THREAD

**Issue by theo-cox** [life-itself/diginomics#40]
We wrote a bunch of stuff for the Web3 project about/relevant to mechanism design and dignomics

## Acceptance

- [ ] Review Web3 content
- [ ] Gather relevant content
- [ ] Refactor and process into dignomics site

## Tasks

- [ ] Relevant content list **Public goods problem analysis directly talks about some of the most prominent Web3 mechanism design: https://web3.lifeitself.org/claims/can-solve-public-goods-problem  Alternative currencies bit of financlaizing value has some relevant stuff, bit this would need a bit more adapting and processing: https://web3.lifeitself.org/claims/can-financialize**
- [ ] ...
