### ISSUE TITLE
Get a list of all our existing lists of models

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#41]
List (and excerpt model summaries into this one post) all our existing lists of models.

TODO: extract notes from #36 (and meeting notes).

## Acceptance

Post with

- [x] Intro / motivation (signposting we are doing a consolidation)
- [x] the list of places we have models already
- [x] Model details / summary from those places excerpted

**Post here: https://github.com/life-itself/diginomics/blob/main/content/notes/summary-past-work.md**

## Tasks

...

**Comment by theo-cox** [comment]
@rufuspollock post here: https://github.com/life-itself/diginomics/blob/main/content/notes/summary-past-work.md

Will let you review and tweak before closing the issue

**Comment by rufuspollock** [comment]
@theo-cox great. a few quick thoughts:

- I suggest post this as a blog post if we can with you and me as authors
- if you could excerpt from slide deck - perhaps just screenshots of key pages that would be nice. Rather than just linking to it.
- the iMed horizon scan report had a nicer / fuller table further down that i think we could excerpt as well below the bullet list e.g. "and in fuller detail with examples:" {insert table}. (BTW you should be able to copy and paste from the original markdown).

**Comment by theo-cox** [comment]
FIXED. Posted with above edits.

**Comment by rufuspollock** [comment]
@theo-cox 👏 one small thing is i don't see this as a post - https://diginomics.io/news isn't showing it. To have a blog post you just need to add `type: Blog` or moving to the news directory in content.

**Comment by theo-cox** [comment]
@rufuspollock that's off because I have added type: blog?

**Comment by rufuspollock** [comment]
@theo-cox it's case sensitive i suspect. So is it `blog` or `Blog`?

**Comment by theo-cox** [comment]
@rufuspollock Latter. I directly copy/pasted from the bread making blog so it shouldn't be a formatting problem

**Comment by rufuspollock** [comment]
@theo-cox the reason it is not showing up is the site build failed. You can notice this by looking at the repo page:

![image](https://user-images.githubusercontent.com/180658/225017079-3125d656-9afd-4d40-bf62-0e9236436bee.png)

If you click on X you get some info - though you have to login to cloudflare for that unfortunately.

Having logged in here is the error. This is cause by an issue with html tags somewhere (mdx is very sensitive to html tags sadly!)

```
00:21:51.552 | • "notes/summary-past-work.md": UnexpectedMDXError: Error: Build failed with 1 error:
-- | --
00:21:51.552 | _mdx_bundler_entry_point-e9b0f8d0-57f3-4d30-a9c1-5630cedfa244.mdx:29:3: ERROR: [plugin: @mdx-js/esbuild] Expected a closing tag for `</strong>` (29:4-29:8) before the end of `paragraph`
```

I've fixed the problem - see commit https://github.com/life-itself/diginomics/commit/dea72a45ba280d2a21065a452928693076b948a9#diff-9e8d38dca2eba65b9199ffa5b467ecfecff589d97b08228c6b0581fe919a9b38R28-R74

###  What's the issue and how do you fix in future

I think the issue is caused by having html tags where the closing tag is not on same line or same indent

So this works:

```<td>some text ...</td>```

```
<td>
  some text ...
</td>
```

But this does **not** work

```<td>some text ...
</td>
```

**Comment by rufuspollock** [comment]
FIXED. See https://diginomics.io/notes/summary-past-work 👏🎉
