### ISSUE TITLE
Migrate openrevolution stuff from Gitlab (gitlab.com/open-world) here to Github (github.com/open-revolution)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#5]
Move open revolution stuff from https://gitlab.com/open-world to https://github.com/open-revolution

Also a chance to tidy and refactor stuff.

## Acceptance

* [x] Migrated https://gitlab.com/open-world/openrevolution.net **DONE: moved to this repo https://github.com/open-revolution/openrevolution.net. Was simple git move with a little bit of tidying for git lfs**
* [x] Migrate https://gitlab.com/open-world/research/ **DONE: see https://github.com/open-revolution/research and #6 for follow up**
* [x] Migrate general "notebook" style repo **DONE. moved to a private repo here for now and will get gradually processed - see #9**
* [x] Migrate open revolution book repo (data-revolution)
* [x] Migrate imedproject.com **DONE. Archived a private full history version plus a clean-history public version here https://github.com/open-revolution/imedproject.org. Follow up issue is #2 **
* [x] Migrate open-leaders.com repo **DONE: https://github.com/open-revolution/open-leaders.com**

## Tasks

* [x] Make a list of all the repos / material to move **DONE. 5 repos and all listed in acceptance** 
* [x] Analyse each one and create an issue (or do/discard if simple)

Implement

* [x] Migrate https://gitlab.com/open-world/openrevolution.net 
* [x] #6 
* [x] Migrate the general open-world (notebook) repo
* [x] Migrate open revolution book repo (data-revolution)
* [x] Migrate imedproject.com
  * [x] Create repo and push
  * [x] Fix LFS stuff
