### ISSUE TITLE
1st tweet introducing diginomics

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#52]
Short essays introducing the topic

**UPDATE: 2023-03-27 already have 3 good options. Just need to act 🚢. Suggest taking 16 Jan one (see below)**

## Tasks

- [x] ➕2023-03-23 consolidate and review existing material from #36 (now in [content scratch doc](https://docs.google.com/document/d/1Pdgf4nTGgnBMxkGi3b0SKfNfBe8RFUf9oyp12zpHOUw/edit#heading=h.5zxbabuvitkq)
  - [x] trailer posts drafts **✅2023-03-23 see [section in scratch](https://docs.google.com/document/d/1Pdgf4nTGgnBMxkGi3b0SKfNfBe8RFUf9oyp12zpHOUw/edit#heading=h.3j15j4p783z8)**
  - [x] 1st essay notes **✅2023-03-27 have 2-3 drafts**
- [x] Pick one to refine **🚧2023-03-27 can start with my original draft from jan**
- [x] Post it **✅2023-04-12 https://twitter.com/rufuspollock/status/1645806810123898887**

### Final - 2023-04-11

I've studied the digital economy for over 20 years as a leading researcher, consultant and entrepreneur. I'm distilling key principles I've learned into a simple guide.

Sign up for free early access here 👇

diginomics.io/guide

---

Learn the rules of the digital economy from an expert

### Versions - 2023-04-14

v1 I'm distilling everything i've learned over twenty years about tech and digital economy into a simple guide.

v1.2 [design principles] I'm distilling key design principles for digital economy into a simple guide. Sign up for early free access here 👇

(Optional Context): Cambridge research fellow, #opendata pioneer, adviser to some of largest governments and companies, and digital social entrepreneur, founder of leading digital NGO and a data business.

v2 I've spent over twenty years studying the digital economy - as Cambridge research fellow, adviser to some of the world's largest governments and companies, and founder of a leading digital NGO and a data business.

I'm distilling everything I've learned into a simple guide. Sign up for free early access here 👇

v3 I've studied digital economy for over 20 years as researcher, consultant to govs and companies and as a successful social entrepreneur. I'm distilling the key principles learned into a simple guide. Sign up for free, early access here

v3.1 I'm distilling 20 years of study into how digital economy works into a simple guide. Sign up for free early access here 👇

v3.1.1 I'm distilling 20 years of study into how digital economy works as researcher, consultant and entrepreneur into a simple guide. Sign up for free early access here 👇

v3.1.2 I'm distilling 20 years of studyᵃ into how digital economy works into a simple guide. Sign up for free early access her

ᵃ Cambridge research fellow, consultant to leading govs, companies and NGOs (including US, EU, Finland, World Bank)   

variant 2

- credibility
  - ...
  - [with details] as top-flight researcher, adviser (majority G7, EU, World Bank, NGOs) and entrepreneur (@okfn
- what:
  - key design principles of digital economy
  - how the digital economy works
  - what i've learned about how digital economy work
- CTA
  -  Sign up for free early access here 👇

Credibility

- Fellow at Cambridge studying
- wrote one of the first papers on regulating google
- Global pioneer open data policy
- Advised majority of G7

### Best option so far

I'm distilling everything i've learned over twenty years[^1] about tech and digital economy into a simple guide.

[Call to action e.g.]

- If you're interested sign up for early access here
- Follow this account
- Send me a DM
- Sign up to this mailing list

[^1]: [Proof of expertise] as an academic, entrepreneur and adviser to governments.  

v1

Hi I'm Rufus, I've spent twenty years studying and working in the digital economy. I've taught at Cambridge University, created successful startups and advised leading governments and companies.

v0.1

Hi I'm Rufus, I write about the digital  business and policy 

#### Tweet 2

Here's what I've learnt 👇

- Diginomics is different! ... from the normal economics you got taught in school or read in the newspaper. For example, normal economics is all about limited resources but in a digital world you can share your creation with the whole world with the click of a button (we call this costless copying!)
* Diginomics is the future: right now there are two economies: an economy of atoms  (the physical economy) and an economy of bits (the digital economy). One is a legacy way and one is the future.
* There are are some simple principles of diginomics (i.e. of digital economy and digital businesses) ... but you need to switch your mental model
* Once you switch your mental model it's easy

**Comment by rufuspollock** [comment]
FIXED. Tweet sent.
