### ISSUE TITLE
Issue gardening plus 6w roadmap for diginomics - 2023-03-23

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#54]
We want to clean up issue tracker and have clear plan of work for next 6w.

## Acceptance

- [x] Issue gardening
  - [x] convert nice to have "idea" issues into discussion forum items (more appropriate and reduces noise in issue tracker)
  - [x] close out (mainly process old notes from sprint) #36
- [x] Process next steps from yesterday meeting in https://docs.google.com/document/d/1LyBkPoCRVgC0ULlOVdyxhlxHfQgBOFGyA5sB9-vZJ_w/edit#
- [x] Consolidate roadmap
  - [x] #19 - top level
  - [x] #22 - main thought work
  - [x] #52 and #35  - main comms work

## Tasks

- [x] Status of "[Data is different post draft](https://docs.google.com/document/d/17Kvy1BGFx33aKIi30Vt1PsSnYAOJplZrxAoWVjlZEOE/edit)" **ready to post with minor additions/tweaking**
- [x] 2 mechanism design posts in [content folder](https://drive.google.com/drive/folders/1b9aVJMljq-ElAwKMsfJVuViRyqJsTIC0) **One a dep draft - have named as such**

**Comment by rufuspollock** [comment]
FIXED. Completed this last Thursday in a bit session with Theo and have a clear roadmap for guide etc in #19
