### ISSUE TITLE
Distill the subject of diginomics (the essence)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#56]
Distill the essence of diginomics: what are we about exactly.

<div align="center">

Learn the rules of the digital economy [aka digital economics]

So that ...

You can design better business models / digital ecosystems
</div>

## What for Whom?

<img src="https://user-images.githubusercontent.com/180658/227927298-29deed8e-2893-4ff7-919d-089711731007.png" height="300">

## Tasks

- [x] Big choice: is our focus on people starting businesses or policymakers or stakeholders who want to a design a digital ecosystem so it is sustainable and flourishing or even who want to design an entire economy? **Theo: definitely the middle one**
- [ ] Issues
  - [x] You learn *economics* (the rules) so that you can build an X (business, ecosystem, economy, market)
  - [x] What is the name for the core thing we are designing? Is it a business model (or value system or ecosystem ...) **✅2023-04-05 yes, a business model (more general term would be ecosystem but that is weird for most people)**

### Visions

- V1 Learn the rules of digital economy
- V2 Learn the rules of the digital economy and how to use them to increase access to just about anything [digital stuff [that matters]]
- V3 Learn the rules of the digital economy and how to use them to … build a successful business or design an entire digital economy
  - [Design] Build a successful business
  - Design a digital ecosystem
  - Design a digital economy
  
#### Also rans

The rules of digital economy and how to fund innovation and access
and what they mean for funding innovation [data, software] and promoting access.
what they mean for designing successful business model
How to fund innovation and promote access to digital goods and services.
Especially if you are policy-maker or want to make open stuff.

#### In nerdy language

The rules of digital economy
And … 
Production and distribution of digital goods
-> production of and access to digital goods
-> increase access to digital goods like software and data

### Brainstorming

|    | Money                                                                             | Digital Economics                                                                                                                                                                | Digital business models                                           |
| -- | --------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| V0 | money                                                                             | digital economics                                                                                                                                                                | Digital business models                                           |
| v1 | investing money                                                                   | rules of the digital economy                                                                                                                                                     | Designing “business” models for digital                           |
| v2 | investing money in your 20s.                                                      | rules of digital economy and what they mean for business model/mechanism design                                                                                                  | Designing digital business models for databases                   |
| v3 | investing money in your 20s so you can buy your first rental property in your 30s | rules of the digital economy and what they mean for business model design so that socially important databases and software are sustainably funded and accessible to more people | Designing better models which improve access to information goods |

### Background: getting specific

> For example: let’s say you want to write about “money.”
> 
> It’s fine to start there, but right away you probably realize how BIG the topic of “money” is. “Money” could mean everything from investing money to saving money to picking stocks to buying real estate to even the emotional relationship you have with money as a societal construct. Which means you need to niche down: pick one direction, and get more specific.
> 
> V2: “I want to write about investing money.”
> V3: “I want to write about investing money in your 20s.”
> V4: “I want to write about investing money in your 20s so you can buy your first rental property in your 30s.”

**Comment by rufuspollock** [comment]
FIXED. Next step is to use this in #35
