### ISSUE TITLE
Migrate and integrate research repo into main repo

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#6]
https://github.com/open-revolution/research/ contains research-y stuff and can move here in this main repo.

## Acceptance

- [x] Repo is now on github **✅2021-??-??**
- [x] Content is integrated into notes/wiki section of this repo **✅2023-01-19 moved to `/notes/` section e.g. https://diginomics.io/notes/research**
- [x] Archived the repo (one day we can delete) **✅2023-01-19 - see archive notice on https://github.com/open-revolution/research**

## Tasks

Migrate

- [x] Migrate to github from https://gitlab.com/open-world/research **✅2023-01-06 - 1y+ ago https://github.com/open-revolution/research**

Integrate

- [x] Assess the materials and where it could go (e.g. files, discussions, issues)
- [x] Make a plan
- [x] Merge this into this repo in `content/notes`

### Current content

- [x] README.md - overview of idea of research on open world. Relatively generic **✅2023-01-19 merged readme and program together into page `/notes/research/`**
- [x] PROGRAM.md - start of a research program outline. This and README could go together.
- [x] imed/proposals-summary.md - this contains early detailed evaluation of specific IMED-style proposals. Most of this ended up in https://imedproject.org/horizon-scan/. Some additional detail but could probably drop.
- [x] notes **✅2023-01-19 ended up keeping all of them as may as well.**
	- [x] README.md ⏭️ split into individual notes **✅2023-01-19 split into 2 notes**
	- [x] adoption-rates.md 💬 only content is tiny stuff re printing press. frankly let's just drop.
	- [x] art-and-ip-problems.md ⏭️ migerate to art-ip-and-holdup-problems.md
	- [x] economist-2015-time-to-fix-patents.md ⏭️ migrate
	- [x] gov-funding-of-open.md ⏭️ migrate to government-funding-of-open-source-examples.md
	- [x] hepatitis-c.md ⏭️ drop as no content
	- [x] markets-and-information-goods.md ⏭️
	- [x] medical-innovation-convention: rndtreaty4.pdf **✅2023-01-19 created page and linked to pdf**

**Comment by rufuspollock** [comment]
FIXED. All done. See acceptance notes above.
