### ISSUE TITLE
[epic] Guide: Designing digital good business models

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#70]
- Hypothesis tree and guide plan: https://coggle.it/diagram/ZDUQAUGwolWedD7a/t/designing-business-models-for-diginomics-101-subtree-here
- Original coggle with SCQA and v0.1 Hypothesis tree (Jan 2023): https://coggle.it/diagram/Y7wv5r1Eo51jzYBJ/t/diginomics-101

## Excalidraw sketch (various iterations jan 2023 to march 2023)

Summary excalidraw with sketch of guide layout: https://link.excalidraw.com/l/9u8crB2ZmUo/AS49XMqTYbf

## Guide outline 2023-03-30

**🚩 sort of deprecated now as replaced by coggl plan above**

What is our goal 2023-03-30? **Here's a guide to designing the business model for a database of emission data** (Aside: why emissions data? not important, we just want a concrete example)

- [ ] Executive summary (last)
  - [ ] Visual summary sketch of the below incorporating short text summaries, links to existing published material and any existing visual material (even if unpolished) **🚧2023-03-30  in https://link.excalidraw.com/l/9u8crB2ZmUo/AS49XMqTYbf**
- [x] [Why, What] Production and supply of emissions data (digital goods in general) requires a different set of guiding principles and a richer/alternative set of approaches because digital goods are fundamentally different from "normal" goods [in being ~ costlessly copyable and having active disincentives for production/supply] 
  - [x] Data is "data"! (emissions data is data) **💬2023-03-30 so obvious you could skip but worth a slide in a presentation**
  - [x] Data is different (digital is different) #60 
  - [x] Difference matters in X, Y way
    - [ ] Check your "mental worldview" at the door
- [x] [How] There are 6 basic archetypes for production and supply of emissions data (digital goods) and there are these criteria for assessing which are usable in which combination. [Designing socio-economic systems for digital information/data [Diginomics system design] builds on these 4 archetypes which can be combined in Z ways.] #22 
  - [x] 🔥 Introduction to business models and terminology #39 
  - [x] How to assemble from building blocks (? even optional - don't have to explain in some mathematical way that X constraints lead to Y options - can be an appendix later)
  - [x] 🔥 Resulting typology / taxonomy: i.e. list of models with a page for each model 
    - [ ] visual overviews e.g. tree of models explaining 
- [ ] Evaluation system (in general) (how do you assess model) aka "Features" e.g. access, social value etc [optional]
  - [ ] Bonus is diagrams that rank by feature or that show how to choose a model by the features you want (e.g. you want open, then you have this)
- [ ] How to choose for you "The discerning model buyer's guide to the best models" 😉 (nb: may move this to front at end!)
  - [ ] What key factors about your situation to consider
  - [ ] What features do you care about
  - [ ] Well, here is the shortlist ranked by X

## Original outline of guide (coggle jan 2023)

Overall outline of plan of work: https://coggle.it/diagram/Y7wv5r1Eo51jzYBJ/t/diginomics-101

![image](https://user-images.githubusercontent.com/180658/228814152-cf7a479c-fdf7-491d-b15e-e5c78b9b4320.png)

![image](https://user-images.githubusercontent.com/180658/228814422-18958ef9-0bfb-4eac-8093-b9ba7e5246bd.png)
