### ISSUE TITLE
[epic] Guide: Diginomic Policy

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#71]
Diginomic Policy Guide aka Designing Digital Economies

- [ ] 101 version (email course)
- [ ] Full version: design your own information economy

## 101 version

- [ ] Diginomics 101
- [ ] Social implications
- [ ] Policy options
- [ ] Intro to remuneration rights for the information commons

<img width="817" alt="image" src="https://user-images.githubusercontent.com/180658/232828752-21bfdf04-6fef-4e43-beb4-e6f6bb02035d.png">
