### ISSUE TITLE
[epic] Guide: Diginomics 101 "Learn the Rules of the Digital Economy"

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#72]
Create a Diginomics 101 taster course.

https://diginomics.io/guide

## Acceptance

- [ ] Skeleton: https://coggle.it/diagram/ZD5u1yHgHRe83f1v/t/diginomics-101
- [ ] Flesh it out
- [ ] Email course
- [ ] Announce and get traffic
- [ ] Iterate

**Comment by rufuspollock** [comment]
@theo-cox know you may be drafting tomorrow so to confirm: aim in first pass on write up is 

- we are writing this as an email course (like the email course demo we had)
- so ~5 core emails (plus a day 0 lead-in plus optional follow-ups)
- So this isn't an essay so much as X emails of 800-1200 words (~ one email for each major branch plus day 0 email trailer).
  - though of course this can look like an essay if you want! (we can just turn each email into a major section etc)

**Comment by theo-cox** [comment]
First draft done : Days 0-4 + Bonus totaling close to 7000 words. See: https://docs.google.com/document/d/1QDGAeQCmNHCXIh4FBdWvSUL8YHzDaOlUaWvpsKR4V6Y/edit

**Comment by rufuspollock** [comment]
@theo-cox will review this afternoon.

**Comment by laurenwigmore** [comment]
@rufuspollock wasn't sure whether to add these updates here or on /onboarding#14

- Watched [YouTube video](https://youtu.be/Em1l0QcR214) - and notes on hack.md [here](https://hackmd.io/WpKf8uMjRjW2sKmLx0x1cg?both)

- Have been adding/editing using suggestion mode on diginomics v1 doc - will continue on with this tomorrow in-between our meetings.
