### ISSUE TITLE
Diginomics 101 landing page v1 (also landing page for site)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/diginomics#84]
Landing page for diginomics 101 course / guide. For now this will also be the home page.

## Acceptance

- [x] Copy written **✅2023-05-02 see [gdoc](https://docs.google.com/document/d/1TSd5-zn6idBk7NelPGlFn3aXgifCa60AFashyoR2XW4/edit#heading=h.jmlu4jgq697p)**
- [x] Wireframe
- [ ] Implemented
- [ ] Live on home page

## Tasks

- [x] Write copy for front page ... **Copy drafted here: https://docs.google.com/document/d/1TSd5-zn6idBk7NelPGlFn3aXgifCa60AFashyoR2XW4/edit#heading=h.jmlu4jgq697p**
  - [x] hero section drafted
  - [x] features and more detail
- [x] Form for signup (as component?) - cf https://github.com/datopian/flowershow/discussions/469
- [ ] Wireframe - see https://link.excalidraw.com/l/9u8crB2ZmUo/5FmgFbVVClb
- [ ] Implement
