### ISSUE TITLE
 Email Course: setup in Brevo (SendinBlue)

### ISSUE THREAD

**Issue by theo-cox** [life-itself/diginomics#86]
Work out - by doing it - how to setup a simple email course in Brevo.

- Started when you sign up e.g. with a form
- Sent a first email
- Sent the next one a day later (or BONUS early at request)
- ...

Can start with a trial run by creating the course from e.g. two input emails. ie. given two emails in markdown in a gist or github repo have a little course

Next part would be documenting or doing the setup for the full course.

## Job Stories

When i have a course drafted i want to copy it over as quickly as possible

- draft in gdocs (or markdown)
- want to add standard footer (e.g. re unsubcribe, other materilas etc)

When i revise my course i want to update my existing emails as easily as possible

- implies that doing first job story kind of again easily is important

## Acceptance

Tryout

- [x] Create two simple emails (can come from our course or otherwise) **✅2023-05-17 see the repo**
- [x] "course" (automation) created with templates based on those emails
  - [x] At least email template creation / updating should be automated

Tooling and docs

- [x] Script or docs for how to create the course (can be very short if obvious in brevo) **🚧2023-05-17 see automation how to below**
- [x] Have a script for updating the course content
- [x] Have docs on how to update content

## Tasks

Test email course

- [x] Is the email course in our public repo? **✅2023-05-16 Not for now**
- [x] Create a private git repo **✅2023-05-16 using the brevo-utils repo**
- [x] Export some of text to markdown and add to repo (2 files)
- [x] Create the course i.e. the automation **✅ 2023-05-18**
  - [x] create a test form in brevo - [Test course form](https://1ebb0834.sibforms.com/serve/MUIEAAjImvszeymyGEDXo-7uXRDRo__I8-w9BBiQaqPDKW03k1qJU0FBdlxdOjS-mBmtsq45uj5PU7oU4YL6MlP4NNbi2dsKlrW3_RDK8AnEvTc5nt-mjq5uP4btfLCiDt1r2UOjWZifr27HTzw5dfyopmHwu9Nr-eiJ7w8Wfk_TGr1lrjRjs-NOjXttUqNNqpBl1lvkLe7XRTp9)
  - [x] create test list - Course test list (in diginomics)
  - [x] create automation - Course test
  - [x] Automation sends 3 emails currently setup with 1min delay
  - [x] Add docs for automation in README https://github.com/life-itself/brevo-utils#creating-a-course-automation-workflow-in-brevo
- [x] Script for adding / updating the templates ** ✅ 2023-05-18**
  - [x] 3 files at `diginomic-101/ ...day-0.md ...day-1.md ...day-2.md`
  - [x] add necessary frontmatter for template title, subject, etc.
  - [x] day-0.md as first welcome email sent immediately after signup

### Email creation howto / notes

- [x] Sendinblue/Brevo doesn't seem feasible for this kind of editing. See: https://newsletter2go-help-en.sendinblue.com/create-newsletters/newsletter-editor/can-i-copy-content-from-a-word-doc-into-my-email.html
  - [x] I don't have tech knowhow to see but this could be an option: https://github.com/eastenluis/markdown-email-editor
  - [x] You can edit in HTML it seems if that works...

Means you need to use the inbuilt editor and do things internally. Quickstart guide to the editor: https://help.brevo.com/hc/en-us/articles/360016831820-Drag-Drop-Editor-New-design-Part-1-Editor-Overview-

### Alternatives

- [x] Convertkit? https://convertkit.com/resources/blog/create-an-email-course **✅2023-05-29 ❌ staying with brevo as found a route to do this**
- [x] Mailcoach is 9.99/month and seems to allow this (and has automation) **✅2023-05-29 ❌ see previous**
    - https://mailcoach.app/pricing
    - https://mailcoach.app/blog/4-writing-a-newsletter-in-markdown-on-mailcoach

## Automation Howto

For the Diginomics 101 course we want to send 5 emails over 5 days, triggered when people sign up.

This makes use of Brevo's automation features: https://www.sendinblue.com/blog/email-automation/#what-are-automated-emails

The process is fairly simple. Login and navigate to the automation section on the side menu and create a new automation. The key things are:

### An entry point: this is the trigger that starts the email. 

![image](https://user-images.githubusercontent.com/72795023/236421385-b2f38a36-b786-45f0-8f09-89ab761ecfe0.png)

We'll want to select the diginomics 1010 signup form: 
![image](https://user-images.githubusercontent.com/72795023/236421477-69d55e8d-4931-4a51-bd17-eeaf86c7110e.png)

### Workflow steps: these are the ordered steps triggered by the entry condition. They can be chained together using the little "+" icon

![image](https://user-images.githubusercontent.com/72795023/236421894-0b480f8a-7ae2-43f4-a42b-4a50fbe36852.png)

We basically just need to automate sending an email and a wait condition equaling 1 day.

Each new email will require a new template:

![image](https://user-images.githubusercontent.com/72795023/236422157-f06c3103-6d82-4155-b67d-3504bf344173.png)

And the wait can be set under "conditions"

![image](https://user-images.githubusercontent.com/72795023/236422215-ba16d55a-6655-4d89-a5ac-cb3721f20d4a.png)

### Final thing is to test the workflow - click the little the little conical flask icon (top right of screeenshot) and enter test email

![image](https://user-images.githubusercontent.com/72795023/236422429-384991cb-85db-4926-8739-04841ecac232.png)

You're then good to go!

**Comment by theo-cox** [comment]
@rufuspollock @khalilcodes see here for automation notes

**Comment by rufuspollock** [comment]
@khalilcodes you can't use markdown directly in brevo but maybe we can hack this via api using html - see https://developers.brevo.com/reference/createsmtptemplate

```javascript
const SibApiV3Sdk = require('sib-api-v3-sdk');
let defaultClient = SibApiV3Sdk.ApiClient.instance;

let apiKey = defaultClient.authentications['api-key'];
apiKey.apiKey = 'YOUR API KEY';

let apiInstance = new SibApiV3Sdk.TransactionalEmailsApi();

let smtpTemplate = new SibApiV3Sdk.CreateSmtpTemplate();

smtpTemplate.sender = {"name":"John Doe","email":"example@example.com"};
smtpTemplate.templateName = "Example Template";
smtpTemplate.htmlContent = "<html><body><h1>This is my first transactional email</h1></body></html>";
smtpTemplate.subject = "New Subject";
smtpTemplate.replyTo = "replyto@domain.com";
smtpTemplate.toField = "example@example.com";
smtpTemplate.isActive = true;
smtpTemplate.attachmentUrl = "https://example.net/upload-file";

apiInstance.createSmtpTemplate(smtpTemplate).then(function(data) {
  console.log('API called successfully. Returned data: ' + JSON.stringify(data));
}, function(error) {
  console.error(error);
});
```

**Comment by khalilcodes** [comment]
@rufuspollock script moved to https://github.com/life-itself/create-template

**Comment by khalilcodes** [comment]
@rufuspollock updated tasks for script and automation. Basically the steps are creating templates (for each days) and then adding those in the automation workflow.

**Comment by rufuspollock** [comment]
@khalilcodes great. and what was the bug with the template creation in the end?

**Comment by rufuspollock** [comment]
FIXED. Have a working script, follow up more ambitious workflow in #93
